version: "3.8"

services:
#  db:
#    container_name: "postgres"
#    image: postgres
#    restart: always
#    environment:
#      - POSTGRES_DB=twitter_clone
#      - POSTGRES_PASSWORD=!1234QWER
#    ports:
#      - "5432:5432"
#    volumes:
#      - ./dbdata:/var/lib/postgresql/data
#
#  adminer:
#    container_name: "adminer"
#    image: adminer
#    restart: always
#    ports:
#      - "8080:8080"

  api:
    container_name: "api"
#    depends_on:
#      - db
    build:
      context: .
      dockerfile: Dockerfile
    command: ["uvicorn", "api.main:app", "--reload"]
    restart: always
    ports:
      - "8000:8000"

  nginx:
    container_name: "nginx"
    depends_on:
      - api
    image: nginx
    volumes:
      - .nginx.conf:/etc/nginx/nginx.conf
      - .static:/usr/share/nginx/static
    ports:
      - "80:80"
