version: "3.9"

services:
#  db:
#    container_name: "postgres"
#    image: postgres
#    restart: always
#    environment:
#      - POSTGRES_DB=twitter_clone
#      - POSTGRES_PASSWORD=!1234QWER
#    ports:
#      - "5432:5432"
#    volumes:
#      - ./dbdata:/var/lib/postgresql/data
#
#  adminer:
#    container_name: "adminer"
#    image: adminer
#    restart: always
#    ports:
#      - "8080:8080"

  api:
    container_name: "api"
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn api.main:app --reload --port 8000 --host localhost
    restart: always
    ports:
      - "8000:8000"

  nginx:
    container_name: "nginx"
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/usr/share/nginx/html/static
    ports:
      - "80:80"
