version: '3.8'

services:
  db:
    container_name: "db"
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=twitter_clone
      - POSTGRES_PASSWORD=!1234QWER
    ports:
      - "5432:5432"
    volumes:
      - ./dbdata:/var/lib/postgresql/data
      - ./confs/postgresql/my_postgresql.conf:/etc/postgresql/postgresql.conf
      - ./logs/postgresql/log-volume:/var/log/postgresql

  adminer:
    container_name: "adminer"
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  twitter:
    container_name: "twitter"
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./alembic/versions:/alembic/versions
      - ./static:/static
      - ./twitter_api:/twitter_api


  nginx:
    container_name: "nginx"
    depends_on:
      - twitter
    image: nginx
    volumes:
      - ./confs/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./static:/static
    ports:
      - "80:80"
